#!/usr/bin/env node
// penpot-kit code emitters.
//
//   node scripts/emit/index.js --ir .penpot/ir.json --out src/design --targets css,dtcg,tailwind,react
//
// Deterministic: same IR in, same bytes out. Codegen must NEVER run through the model,
// or every regeneration costs tokens and drifts between runs.

const fs = require("fs");
const path = require("path");

// ---------- shared helpers ----------

const PX_TYPES = new Set(["spacing", "borderRadius", "borderWidth", "sizing", "fontSizes", "dimension"]);

const varName = (n) => "--" + String(n).replace(/\./g, "-");

// Penpot writes references as {token.name}. Preserve them as var() so the token CHAIN
// survives into CSS. Flattening a reference to a literal is exactly what makes
// Penpot's own generateStyle output unmaintainable.
const refToCss = (value, type) => {
  const s = String(value);
  if (/^\{.+\}$/.test(s)) return "var(" + varName(s.slice(1, -1)) + ")";
  if (PX_TYPES.has(type) && /^-?\d+(\.\d+)?$/.test(s)) return s + "px";
  return s;
};

const kebab = (s) => String(s)
  .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
  .replace(/[\s_.]+/g, "-")
  .toLowerCase();

const pascal = (s) => String(s)
  .replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
  .replace(/^(.)/, (m) => m.toUpperCase());

const banner = (kind) =>
  "/* GENERATED by penpot-kit from Penpot. Do not edit by hand.\n" +
  "   Regenerate with /penpot:codegen   |   target: " + kind + " */\n";

// Which token names actually change between themes? Only those need theme blocks.
// The theme switch point is ONLY the alias layer: the same token NAME declared in more
// than one set with different values (e.g. color.neutral.background.1 in both Alias/Light
// and Alias/Dark). Those must be re-declared per theme with resolved values, because CSS
// has no equivalent of Penpot's set scoping.
//
// Everything else -- Global literals AND the Semantic layer -- keeps its authored
// {reference} and is emitted as var(), which is what preserves the token chain:
//   --button-primary-background-rest: var(--color-brand-background-rest);
// A semantic token then re-themes automatically through the alias it points at, and a
// rebrand stays a one-token edit. Flattening these to hex defeats the architecture.
function dynamicNames(ir) {
  const bySet = {};
  for (const t of ir.tokens.values) {
    (bySet[t.name] = bySet[t.name] || []).push(String(t.value));
  }
  const out = new Set();
  for (const name of Object.keys(bySet)) {
    const vals = bySet[name];
    if (vals.length > 1 && new Set(vals).size > 1) out.add(name);
  }
  return out;
}

// ---------- target: CSS custom properties ----------

function emitCss(ir) {
  const byTheme = ir.tokens.resolvedByTheme || {};
  const themes = Object.keys(byTheme);
  const base = themes[0];
  const others = themes.slice(1);
  const dynamic = dynamicNames(ir);

  const decls = ir.tokens.values;
  const stat = decls.filter((t) => !dynamic.has(t.name));
  const dyn = decls.filter((t) => dynamic.has(t.name));

  // Deduplicate: the same alias name exists in BOTH alias sets. Keep one declaration
  // per name, since CSS has no notion of Penpot's set scoping.
  const seen = new Set();
  const dynUnique = dyn.filter((t) => (seen.has(t.name) ? false : (seen.add(t.name), true)));

  let out = banner("css variables") + "\n:root {\n";
  stat.forEach((t) => {
    out += "  " + varName(t.name) + ": " + refToCss(t.value, t.type) + ";\n";
  });

  if (dynUnique.length && base) {
    out += "\n  /* " + base + " theme (default) */\n";
    dynUnique.forEach((t) => {
      out += "  " + varName(t.name) + ": " + byTheme[base][t.name] + ";\n";
    });
  }
  out += "}\n";

  for (const th of others) {
    const map = byTheme[th];
    const lines = dynUnique.map((t) => varName(t.name) + ": " + map[t.name] + ";");
    out += "\n@media (prefers-color-scheme: dark) {\n";
    out += '  :root:not([data-theme="' + kebab(base) + '"]) {\n';
    lines.forEach((l) => { out += "    " + l + "\n"; });
    out += "  }\n}\n";
    out += '\n:root[data-theme="' + kebab(th) + '"] {\n';
    lines.forEach((l) => { out += "  " + l + "\n"; });
    out += "}\n";
  }
  return out;
}

// ---------- target: W3C DTCG tokens.json ----------

const DTCG_TYPE = {
  color: "color", spacing: "dimension", borderRadius: "dimension",
  borderWidth: "dimension", sizing: "dimension", opacity: "number",
  fontSizes: "dimension", fontWeights: "fontWeight", fontFamilies: "fontFamily",
  letterSpacing: "dimension", typography: "typography"
};

function emitDtcg(ir) {
  const root = {};
  const seen = new Set();
  for (const t of ir.tokens.values) {
    if (seen.has(t.name)) continue;
    seen.add(t.name);
    const parts = t.name.split(".");
    let node = root;
    parts.forEach((p, i) => {
      if (i === parts.length - 1) {
        const raw = String(t.value);
        const isRef = /^\{.+\}$/.test(raw);
        node[p] = {
          $type: DTCG_TYPE[t.type] || "other",
          $value: isRef ? raw
            : (PX_TYPES.has(t.type) && /^-?\d+(\.\d+)?$/.test(raw) ? raw + "px" : t.value)
        };
      } else {
        node[p] = node[p] || {};
        node = node[p];
      }
    });
  }
  return JSON.stringify(
    Object.assign({ $description: "Generated by penpot-kit from Penpot" }, root),
    null, 2
  ) + "\n";
}

// ---------- target: Tailwind config ----------

function emitTailwind(ir) {
  const seen = new Set();
  const uniq = ir.tokens.values.filter((t) => (seen.has(t.name) ? false : (seen.add(t.name), true)));
  const pick = (type) => uniq.filter((t) => t.type === type);
  const strip = (arr, prefix) => arr.reduce((a, t) => {
    a[kebab(t.name).replace(prefix, "")] = "var(" + varName(t.name) + ")";
    return a;
  }, {});

  const cfg = {
    theme: {
      extend: {
        colors: strip(pick("color"), /^$/),
        spacing: strip(pick("spacing"), /^space-/),
        borderRadius: strip(pick("borderRadius"), /^radius-/),
        borderWidth: strip(pick("borderWidth"), /^stroke-/)
      }
    }
  };

  return "// GENERATED by penpot-kit from Penpot. Do not edit by hand.\n" +
    "// Values reference CSS custom properties, so runtime theme switching keeps working.\n" +
    "module.exports = " + JSON.stringify(cfg, null, 2) + ";\n";
}

// ---------- target: React + TypeScript ----------

function emitReact(ir, comp) {
  const Name = pascal(comp.name);
  const base = kebab(Name);
  const axes = Object.entries(comp.axes);

  const tokenOf = (sv) => {
    if (!sv) return null;
    return sv.t ? "var(" + varName(sv.t) + ")" : String(sv.v);
  };

  const types = axes.map(([axis, vals]) =>
    "export type " + Name + pascal(axis) + " = " +
    vals.map((v) => JSON.stringify(kebab(v))).join(" | ") + ";"
  ).join("\n");

  const props = axes.map(([axis]) =>
    "  /** " + axis + " — mirrors the Penpot variant axis */\n" +
    "  " + kebab(axis) + "?: " + Name + pascal(axis) + ";"
  ).join("\n");

  const defaults = axes.map(([axis, vals]) =>
    kebab(axis) + " = " + JSON.stringify(kebab(vals[0]))
  ).join(", ");

  const clsLines = axes.map(([axis]) =>
    "    `" + base + "--${" + kebab(axis) + "}`,"
  ).join("\n");

  const tsx = [
    "// GENERATED by penpot-kit from Penpot. Do not edit by hand.",
    "// The prop types are derived from the Penpot variant axes — the design IS the signature.",
    'import type { ButtonHTMLAttributes } from "react";',
    'import "./' + base + '.css";',
    "",
    types,
    "",
    "export interface " + Name + "Props extends ButtonHTMLAttributes<HTMLButtonElement> {",
    props,
    "}",
    "",
    "export function " + Name + "({ " + defaults + ", className, children, ...rest }: " + Name + "Props) {",
    "  const cls = [",
    "    " + JSON.stringify(base) + ",",
    clsLines,
    "    className",
    '  ].filter(Boolean).join(" ");',
    "",
    "  return (",
    "    <button className={cls} {...rest}>",
    "      {children}",
    "    </button>",
    "  );",
    "}",
    ""
  ].join("\n");

  const first = comp.variants[0];
  let css = banner("component css") + "\n." + base + " {\n" +
    "  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n" +
    "  border: 0;\n  cursor: pointer;\n  white-space: nowrap;\n" +
    "  font-family: " + JSON.stringify(first.text.fontFamily) + ", system-ui, sans-serif;\n" +
    "  font-weight: " + first.text.fontWeight + ";\n" +
    "  line-height: " + first.text.lineHeight + ";\n" +
    "  border-radius: " + tokenOf(first.box.radius) + ";\n}\n";

  const axisNames = axes.map((a) => a[0]);
  const sizeAxis = axisNames.find((a) => /size/i.test(a)) || axisNames[1];
  const appearanceAxis = axisNames.find((a) => a !== sizeAxis) || axisNames[0];

  (comp.axes[sizeAxis] || []).forEach((val) => {
    const v = comp.variants.find((x) => x.props && x.props[sizeAxis] === val);
    if (!v) return;
    css += "\n." + base + "--" + kebab(val) + " {\n" +
      "  height: " + v.box.height + "px;\n" +
      "  padding-inline: " + tokenOf(v.box.paddingLeft) + ";\n" +
      "  font-size: " + v.text.fontSize + "px;\n}\n";
  });

  (comp.axes[appearanceAxis] || []).forEach((val) => {
    const v = comp.variants.find((x) => x.props && x.props[appearanceAxis] === val);
    if (!v) return;
    const bg = v.box.fill ? tokenOf(v.box.fill) : "transparent";
    const fg = tokenOf(v.text.color);
    css += "\n." + base + "--" + kebab(val) + " {\n" +
      "  background: " + bg + ";\n" +
      "  color: " + fg + ";\n";
    if (v.box.stroke) {
      css += "  border: " + tokenOf(v.box.stroke.width) + " solid " + tokenOf(v.box.stroke.color) + ";\n";
    }
    css += "}\n";
  });

  return { tsx: tsx, css: css, name: base, Name: Name };
}

// ---------- CLI ----------

function arg(flag, def) {
  const i = process.argv.indexOf(flag);
  return i > -1 ? process.argv[i + 1] : def;
}

function main() {
  const irPath = arg("--ir", ".penpot/ir.json");
  const outDir = arg("--out", "src/design");
  const targets = arg("--targets", "css,dtcg,tailwind,react").split(",").map((s) => s.trim());

  const ir = JSON.parse(fs.readFileSync(irPath, "utf8"));
  fs.mkdirSync(outDir, { recursive: true });

  const written = [];
  const w = (rel, content) => {
    const p = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
    written.push(rel + "  (" + content.length + " bytes)");
  };

  if (targets.includes("css")) w("tokens.css", emitCss(ir));
  if (targets.includes("dtcg")) w("tokens.json", emitDtcg(ir));
  if (targets.includes("tailwind")) w("tailwind.tokens.cjs", emitTailwind(ir));
  if (targets.includes("react")) {
    for (const comp of ir.components || []) {
      const r = emitReact(ir, comp);
      w(r.Name + ".tsx", r.tsx);
      w(r.name + ".css", r.css);
    }
  }

  console.log("Wrote to " + outDir + ":");
  written.forEach((f) => console.log("  " + f));
}

if (require.main === module) main();
module.exports = { emitCss: emitCss, emitDtcg: emitDtcg, emitTailwind: emitTailwind, emitReact: emitReact };
