#!/usr/bin/env node
// penpot-kit app scaffold.
//
//   node scripts/emit/scaffold.js --ir .penpot/ir.json --out app [--name my-app]
//
// Generates a real, buildable Vite + React + TypeScript application wired to the design
// system, including a gallery screen that renders EVERY component at EVERY axis value.
//
// The gallery is not a demo. It is the consistency test:
//
//   * if a component's generated props do not typecheck, `tsc` fails
//   * if two components disagree about a token name, the CSS variable resolves to nothing
//   * if the theme layer is broken, the dark toggle visibly does not switch
//
// A design system that cannot compile its own gallery is not a system yet.

"use strict";

const fs = require("fs");
const path = require("path");

function arg(flag, def) {
  const i = process.argv.indexOf(flag);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

const kebab = (s) => String(s)
  .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
  .replace(/[\s_.]+/g, "-")
  .toLowerCase();
const pascal = (s) => String(s)
  .replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
  .replace(/^(.)/, (m) => m.toUpperCase());
const camel = (s) => kebab(s).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const BOOLY = [["no", "yes"], ["false", "true"], ["off", "on"]];
const isBool = (vals) => {
  if (vals.length !== 2) return false;
  const low = vals.map((v) => String(v).toLowerCase()).sort();
  return BOOLY.some((p) => p[0] === low[0] && p[1] === low[1]);
};
const truthy = (vals) => vals.find((v) => /^(yes|true|on)$/i.test(v));

// Resolve component names the same way the emitter does, so the gallery imports the files
// that were actually written. Getting this wrong produces a gallery that cannot resolve
// its own imports.
function resolveNames(ir) {
  const used = new Map();
  return (ir.components || []).map((c) => {
    let chosen = (c.connect && c.connect.name) || c.name;
    if (used.has(chosen)) {
      let cand = c.page && c.page !== used.get(chosen).page ? c.page + " " + chosen : null;
      if (!cand || used.has(cand)) {
        let n = 2;
        while (used.has(chosen + " " + n)) n++;
        cand = chosen + " " + n;
      }
      chosen = cand;
    }
    used.set(chosen, { page: c.page });
    return { comp: c, Name: pascal(chosen), file: pascal(chosen) };
  });
}

// One JSX example per axis-value combination, capped so a 12-variant component does not
// produce an unreadable wall.
function examples(entry, cap) {
  const { comp, Name } = entry;
  const axes = Object.entries(comp.axes || {});
  if (!axes.length) return ["<" + Name + " />"];

  let combos = [{}];
  for (const [axis, vals] of axes) {
    const next = [];
    for (const base of combos) {
      for (const v of vals) {
        next.push(Object.assign({}, base, { [axis]: v }));
        if (next.length >= cap) break;
      }
      if (next.length >= cap) break;
    }
    combos = next;
  }

  return combos.slice(0, cap).map((combo) => {
    const props = axes.map(([axis, vals]) => {
      const v = combo[axis];
      if (v === undefined) return null;
      if (isBool(vals)) return v === truthy(vals) ? camel(axis) : null;   // bare prop = true
      return camel(axis) + '="' + kebab(v) + '"';
    }).filter(Boolean).join(" ");

    const isButton = /button$/i.test(comp.name);
    const label = isButton ? Name : null;
    return "<" + Name + (props ? " " + props : "") +
      (label ? ">" + label + "</" + Name + ">" : " />");
  });
}

function galleryTsx(ir, entries) {
  const imports = entries.map((e) =>
    'import { ' + e.Name + ' } from "./design/' + e.file + '";').join("\n");

  const sections = entries.map((e) => {
    const ex = examples(e, 12);
    const axes = Object.entries(e.comp.axes || {})
      .map(([a, v]) => a + ": " + v.join(" | ")).join("   ·   ") || "no variants";
    return [
      '      <section className="gallery__section">',
      '        <header className="gallery__head">',
      "          <h2>" + e.Name + "</h2>",
      '          <p className="gallery__axes">' + axes + "</p>",
      "        </header>",
      '        <div className="gallery__row">',
      ex.map((x) => "          " + x).join("\n"),
      "        </div>",
      "      </section>"
    ].join("\n");
  }).join("\n\n");

  const themes = Object.keys(ir.tokens.resolvedByTheme || { Light: 1 });

  return `// GENERATED by penpot-kit. Regenerate: penpot-kit scaffold
//
// This gallery renders every component at every axis value. It is the consistency test:
// if the design system is coherent, this file typechecks and every surface below responds
// to the theme toggle. If it does not, something drifted.
import { useEffect, useState } from "react";
import "./design/tokens.css";
import "./app.css";
${imports}

const THEMES = ${JSON.stringify(themes.map((t) => kebab(t)))} as const;
type Theme = (typeof THEMES)[number];

export default function App() {
  const [theme, setTheme] = useState<Theme>(THEMES[0]);

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);

  return (
    <div className="gallery">
      <header className="gallery__top">
        <div>
          <h1>${ir.file || "Design system"}</h1>
          <p className="gallery__meta">
            ${(ir.components || []).length} components ·{" "}
            ${(ir.components || []).reduce((a, c) => a + (c.variants || []).length, 0)} variants ·{" "}
            ${ir.tokens.values.length} tokens
          </p>
        </div>
        <div className="gallery__themes">
          {THEMES.map((t) => (
            <button
              key={t}
              className={"gallery__theme" + (t === theme ? " is-active" : "")}
              onClick={() => setTheme(t)}
            >
              {t}
            </button>
          ))}
        </div>
      </header>

${sections}
    </div>
  );
}
`;
}

// The gallery's own chrome uses the SAME tokens as the components. If a token name is
// wrong here it is visibly wrong there too, which is the point.
const APP_CSS = `/* GENERATED by penpot-kit. Gallery chrome — uses the design system's own tokens. */

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--color-surface-variant, #f5f5f5);
  color: var(--color-on-surface-base, #242424);
  font-family: Inter, system-ui, sans-serif;
}

.gallery {
  max-width: 1100px;
  margin: 0 auto;
  padding: var(--space-320, 32px);
  display: flex;
  flex-direction: column;
  gap: var(--space-320, 32px);
}

.gallery__top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-160, 16px);
  padding-bottom: var(--space-160, 16px);
  border-bottom: 1px solid var(--color-outline-variant, #cac4d0);
}

.gallery__top h1 { margin: 0; font-size: 28px; font-weight: 600; }
.gallery__meta { margin: 4px 0 0; font-size: 13px; color: var(--color-on-surface-variant, #616161); }

.gallery__themes { display: flex; gap: var(--space-80, 8px); }

.gallery__theme {
  padding: 6px 14px;
  font: inherit;
  font-size: 13px;
  cursor: pointer;
  text-transform: capitalize;
  border-radius: var(--radius-full, 9999px);
  border: 1px solid var(--color-outline-variant, #cac4d0);
  background: var(--color-surface-base, #fff);
  color: var(--color-on-surface-base, #242424);
}
.gallery__theme.is-active {
  background: var(--color-primary-base, #0f6cbd);
  color: var(--color-on-primary-base, #fff);
  border-color: transparent;
}

.gallery__section {
  background: var(--color-surface-base, #fff);
  border: 1px solid var(--color-outline-variant, #cac4d0);
  border-radius: var(--radius-large, 8px);
  padding: var(--space-240, 24px);
  display: flex;
  flex-direction: column;
  gap: var(--space-160, 16px);
}

.gallery__head h2 { margin: 0; font-size: 16px; font-weight: 600; }
.gallery__axes {
  margin: 4px 0 0;
  font-size: 12px;
  color: var(--color-on-surface-variant, #616161);
}

.gallery__row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-160, 16px);
}
`;

function files(ir, name, entries) {
  return {
    "package.json": JSON.stringify({
      name: kebab(name), private: true, version: "0.0.0", type: "module",
      scripts: { dev: "vite", build: "tsc --noEmit && vite build", preview: "vite preview" },
      dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: {
        "@types/react": "^18.3.12", "@types/react-dom": "^18.3.1",
        "@vitejs/plugin-react": "^4.3.4", typescript: "^5.6.3", vite: "^5.4.11"
      }
    }, null, 2) + "\n",

    "tsconfig.json": JSON.stringify({
      compilerOptions: {
        target: "ES2020", lib: ["ES2020", "DOM", "DOM.Iterable"], module: "ESNext",
        moduleResolution: "bundler", jsx: "react-jsx", strict: true,
        noUnusedLocals: true, noUnusedParameters: true, noEmit: true,
        skipLibCheck: true, isolatedModules: true, resolveJsonModule: true
      },
      include: ["src"]
    }, null, 2) + "\n",

    "vite.config.ts":
      'import { defineConfig } from "vite";\n' +
      'import react from "@vitejs/plugin-react";\n\n' +
      "export default defineConfig({ plugins: [react()] });\n",

    "index.html":
      '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n' +
      '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n' +
      "    <title>" + (ir.file || "Design system") + "</title>\n  </head>\n  <body>\n" +
      '    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n' +
      "  </body>\n</html>\n",

    "src/main.tsx":
      'import { StrictMode } from "react";\n' +
      'import { createRoot } from "react-dom/client";\n' +
      'import App from "./App";\n\n' +
      'createRoot(document.getElementById("root")!).render(\n' +
      "  <StrictMode>\n    <App />\n  </StrictMode>\n);\n",

    "src/App.tsx": galleryTsx(ir, entries),
    "src/app.css": APP_CSS
  };
}

function main() {
  const irPath = arg("--ir", ".penpot/ir.json");
  const outDir = path.resolve(arg("--out", "app"));
  const name = arg("--name", "design-system-gallery");

  if (!fs.existsSync(irPath)) {
    console.error("penpot-kit scaffold: no IR at " + irPath);
    process.exit(2);
  }
  const ir = JSON.parse(fs.readFileSync(irPath, "utf8"));
  const entries = resolveNames(ir);

  const written = [];
  const out = files(ir, name, entries);
  for (const [rel, content] of Object.entries(out)) {
    const dest = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content);
    written.push(rel);
  }

  console.log("Scaffolded " + name + " -> " + outDir);
  written.forEach((f) => console.log("  " + f));
  console.log("\n  " + entries.length + " components imported into the gallery");
  console.log("\nNext:");
  console.log("  penpot-kit emit --ir " + irPath + " --out " + path.join(outDir, "src", "design"));
  console.log("  cd " + outDir + " && npm install && npm run build");
}

if (require.main === module) main();
module.exports = { resolveNames, examples, galleryTsx };
